(source gnu)
(source melpa)

;; default
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;;;; add
;; base
(depends-on "auto-install")
(depends-on "helm")
(depends-on "exec-path-from-shell")
(depends-on "vagrant-tramp")
(depends-on "wakatime-mode")
(depends-on "neotree")

;; input
(depends-on "ddskk")
(depends-on "auto-complete")

;; screen
(depends-on "yascroll")
(depends-on "smooth-scroll" :git "https://github.com/k-talo/smooth-scroll.el.git")

;; buffer
(depends-on "anzu")
(depends-on "avy")

;;;; programming
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "popup")

;;;; front-end
(depends-on "web-mode")
(depends-on "coffee-mode")

;; markup
(depends-on "slim-mode")
(depends-on "scss-mode")

(depends-on "markdown-mode")
(depends-on "yaml-mode")